//! Codegen — Phase 1 C-backend.
//!
//! Lowers the supported subset of the AST to portable C99 source.
//! The output is paired with `compiler/runtime.c` and compiled by a
//! host C compiler (`cc`, configurable via `$CC`).
//!
//! Supported in Phase 1:
//!     - Int (`int64_t`), Bool (`bool`), Unit (`void`)
//!     - Top-level functions, parameters, return types of supported types
//!     - `let`, `let mut`, assignment
//!     - Arithmetic, comparison, logical operators
//!     - if-expression, while, `for x in 0..N`, break, continue, return
//!     - Pipeline `x |> f(args)`
//!     - `print(value)` for Int / Bool / Unit
//!     - Recursive calls
//!
//! Out of scope for Phase 1 codegen (emits a clear diagnostic):
//!     Float, String, List, Struct, Enum, Variant, MethodCall, Field,
//!     Index, StructLit, Lambda, Match, Try, Spawn, Await.
//! These ship in Phase 1.3 alongside the LLVM backend.

use std::collections::HashMap;
use std::fmt::Write;

use crate::ast::*;
use crate::diagnostic::{Diagnostic, LangResult, Span};

/// Result of a successful codegen.
#[derive(Debug, Clone)]
pub struct CodegenOutput {
    pub c_source: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum CType {
    Int,
    Bool,
    Float,
    Unit,
}

impl CType {
    fn c_repr(self) -> &'static str {
        match self {
            CType::Int => "int64_t",
            CType::Bool => "bool",
            CType::Float => "double",
            CType::Unit => "void",
        }
    }
}

fn ctype_from_ref(ty: &TypeRef, span: &Span) -> LangResult<CType> {
    match ty {
        TypeRef::Named(name) => match name.as_str() {
            "Int" => Ok(CType::Int),
            "Bool" => Ok(CType::Bool),
            "Float" => Ok(CType::Float),
            _ => Err(unsupported(
                format!("native codegen does not yet support type '{name}'"),
                span,
            )),
        },
        TypeRef::Unit => Ok(CType::Unit),
        TypeRef::Infer => Err(unsupported(
            "native codegen needs an explicit type annotation here",
            span,
        )),
        TypeRef::Generic(name, _) => Err(unsupported(
            format!("native codegen does not yet support generic type '{name}[…]'"),
            span,
        )),
        TypeRef::Function(_, _) => Err(unsupported(
            "native codegen does not yet support function-typed values",
            span,
        )),
        TypeRef::List(_) => Err(unsupported(
            "native codegen does not yet support list types",
            span,
        )),
        TypeRef::Ref(_, _) => Err(unsupported(
            "native codegen does not yet emit reference types — coming in Phase 2.1",
            span,
        )),
    }
}

#[derive(Debug, Clone)]
struct FnSig {
    params: Vec<(String, CType)>,
    return_ty: CType,
}

pub struct Codegen {
    out: String,
    locals: Vec<HashMap<String, CType>>,
    functions: HashMap<String, FnSig>,
    temp_counter: usize,
    indent: usize,
}

impl Codegen {
    pub fn new() -> Self {
        Self {
            out: String::new(),
            locals: vec![HashMap::new()],
            functions: HashMap::new(),
            temp_counter: 0,
            indent: 0,
        }
    }

    pub fn emit_program(mut self, program: &Program) -> LangResult<CodegenOutput> {
        self.collect_function_signatures(&program.items)?;

        if !self.functions.contains_key("main") {
            return Err(Diagnostic::at_start(
                "native codegen requires a top-level `fn main()` to use as the entry point",
            ));
        }

        writeln!(
            self.out,
            "// Generated by the mom compiler. Do not edit by hand."
        )
        .unwrap();
        writeln!(self.out, "#include \"runtime.h\"").unwrap();
        writeln!(self.out).unwrap();

        // Forward declarations
        for item in &program.items {
            if let Item::Function(function) = item {
                self.emit_forward_decl(function)?;
            }
        }
        writeln!(self.out).unwrap();

        // Definitions
        for item in &program.items {
            match item {
                Item::Function(function) => self.emit_function(function)?,
                Item::Const(decl) => {
                    return Err(unsupported(
                        format!(
                            "native codegen does not yet support top-level const '{}'",
                            decl.name
                        ),
                        &decl.span,
                    ));
                }
                Item::Statement(_) => {
                    return Err(Diagnostic::at_start(
                        "native codegen does not allow top-level statements outside a function",
                    ));
                }
                // Module/Import/Trait/Impl/Extern accepted by the front end
                // but their codegen lands in Phase 1.3 / Phase 2.
                Item::Module(decl) => {
                    return Err(unsupported(
                        format!("native codegen does not yet support module '{}'", decl.name),
                        &decl.span,
                    ));
                }
                Item::Import(_) | Item::Trait(_) | Item::Impl(_) | Item::Extern(_) => {
                    // silently accepted; emits no code in Phase 1.
                }
                Item::Struct(decl) => {
                    return Err(unsupported(
                        format!("native codegen does not yet support struct '{}'", decl.name),
                        &decl.span,
                    ));
                }
                Item::Enum(decl) => {
                    return Err(unsupported(
                        format!("native codegen does not yet support enum '{}'", decl.name),
                        &decl.span,
                    ));
                }
            }
        }

        Ok(CodegenOutput { c_source: self.out })
    }

    fn collect_function_signatures(&mut self, items: &[Item]) -> LangResult<()> {
        for item in items {
            if let Item::Function(function) = item {
                let mut params = Vec::with_capacity(function.params.len());
                for param in &function.params {
                    params.push((
                        param.name.clone(),
                        ctype_from_ref(&param.ty, &function.span)?,
                    ));
                }
                let return_ty = ctype_from_ref(&function.return_type, &function.span)?;
                self.functions
                    .insert(function.name.clone(), FnSig { params, return_ty });
            }
        }
        Ok(())
    }

    fn emit_forward_decl(&mut self, function: &FunctionDecl) -> LangResult<()> {
        let sig = self.functions.get(&function.name).cloned().unwrap();
        self.write_signature(&function.name, &sig)?;
        writeln!(self.out, ";").unwrap();
        Ok(())
    }

    fn emit_function(&mut self, function: &FunctionDecl) -> LangResult<()> {
        if !function.generics.is_empty() {
            return Err(unsupported(
                format!(
                    "native codegen does not yet monomorphize generic function '{}'",
                    function.name
                ),
                &function.span,
            ));
        }
        if function.is_async {
            return Err(unsupported(
                format!(
                    "native codegen does not yet support async function '{}'",
                    function.name
                ),
                &function.span,
            ));
        }

        let sig = self.functions.get(&function.name).cloned().unwrap();
        self.write_signature(&function.name, &sig)?;
        writeln!(self.out, " {{").unwrap();
        self.indent = 1;

        self.locals = vec![HashMap::new()];
        for (name, ty) in &sig.params {
            self.locals.last_mut().unwrap().insert(name.clone(), *ty);
        }

        let body_ty = self.emit_block(&function.body, sig.return_ty)?;

        if sig.return_ty != CType::Unit {
            if body_ty != sig.return_ty {
                // already handled per-expr in emit_block
            }
        }

        writeln!(self.out, "}}\n").unwrap();
        self.indent = 0;
        Ok(())
    }

    fn write_signature(&mut self, name: &str, sig: &FnSig) -> LangResult<()> {
        write!(self.out, "{} {}(", sig.return_ty.c_repr(), c_ident(name)).unwrap();
        if sig.params.is_empty() {
            write!(self.out, "void").unwrap();
        } else {
            for (i, (pname, ty)) in sig.params.iter().enumerate() {
                if i > 0 {
                    write!(self.out, ", ").unwrap();
                }
                write!(self.out, "{} {}", ty.c_repr(), c_ident(pname)).unwrap();
            }
        }
        write!(self.out, ")").unwrap();
        Ok(())
    }

    /// Emit a block. Returns the type of the block's tail value (CType::Unit
    /// if the block ends with a statement-form expression).
    fn emit_block(&mut self, block: &Block, return_ty: CType) -> LangResult<CType> {
        self.push_scope();
        let mut tail_ty = CType::Unit;

        let len = block.statements.len();
        for (idx, stmt) in block.statements.iter().enumerate() {
            let is_last = idx + 1 == len;
            tail_ty = self.emit_stmt(stmt, is_last, return_ty)?;
        }

        self.pop_scope();
        Ok(tail_ty)
    }

    fn emit_stmt(&mut self, stmt: &Stmt, is_last: bool, return_ty: CType) -> LangResult<CType> {
        match stmt {
            Stmt::Let {
                name,
                ty,
                value,
                span,
                ..
            } => {
                let (value_src, value_ty) = self.emit_expr_value(value)?;
                let declared_ty = match ty {
                    Some(t) => ctype_from_ref(t, span)?,
                    None => value_ty,
                };
                if declared_ty != value_ty {
                    return Err(unsupported(
                        format!(
                            "native codegen: declared type does not match value type for '{name}'"
                        ),
                        span,
                    ));
                }
                self.indent_line();
                writeln!(
                    self.out,
                    "{} {} = {};",
                    declared_ty.c_repr(),
                    c_ident(name),
                    value_src
                )
                .unwrap();
                self.declare_local(name, declared_ty)?;
                Ok(CType::Unit)
            }
            Stmt::Const(decl) => Err(unsupported(
                format!(
                    "native codegen does not yet support local const '{}'",
                    decl.name
                ),
                &decl.span,
            )),
            Stmt::Assign {
                target,
                value,
                span,
            } => match target {
                AssignTarget::Name(name) => {
                    let (value_src, _) = self.emit_expr_value(value)?;
                    let ty = self
                        .lookup_local(name)
                        .ok_or_else(|| codegen_error(format!("unknown binding '{name}'"), span))?;
                    let _ = ty;
                    self.indent_line();
                    writeln!(self.out, "{} = {};", c_ident(name), value_src).unwrap();
                    Ok(CType::Unit)
                }
                AssignTarget::Field { .. } | AssignTarget::Index { .. } => Err(unsupported(
                    "native codegen does not yet support compound assignment targets",
                    span,
                )),
            },
            Stmt::Return { value, span: _ } => {
                if let Some(value) = value {
                    let (value_src, value_ty) = self.emit_expr_value(value)?;
                    if value_ty != return_ty {
                        return Err(unsupported(
                            format!(
                                "native codegen: return type mismatch (expected {:?}, got {:?})",
                                return_ty, value_ty
                            ),
                            &value.span(),
                        ));
                    }
                    self.indent_line();
                    if return_ty == CType::Unit {
                        writeln!(self.out, "(void){};\n", value_src).unwrap();
                        self.indent_line();
                        writeln!(self.out, "return;").unwrap();
                    } else {
                        writeln!(self.out, "return {};", value_src).unwrap();
                    }
                } else {
                    self.indent_line();
                    writeln!(self.out, "return;").unwrap();
                }
                Ok(CType::Unit)
            }
            Stmt::Expr {
                expr,
                has_semicolon,
                ..
            } => {
                let (src, ty) = self.emit_expr_value(expr)?;
                if is_last && !has_semicolon {
                    // tail expression: emit `return <src>` for non-unit functions
                    self.indent_line();
                    if return_ty == CType::Unit {
                        // discard
                        if ty == CType::Unit {
                            writeln!(self.out, "{};", src).unwrap();
                        } else {
                            writeln!(self.out, "(void){};", src).unwrap();
                        }
                    } else {
                        if ty != return_ty {
                            return Err(unsupported(
                                format!(
                                    "native codegen: tail expression type ({:?}) does not match return type ({:?})",
                                    ty, return_ty
                                ),
                                &expr.span(),
                            ));
                        }
                        writeln!(self.out, "return {};", src).unwrap();
                    }
                } else {
                    self.indent_line();
                    if ty == CType::Unit {
                        writeln!(self.out, "{};", src).unwrap();
                    } else {
                        writeln!(self.out, "(void){};", src).unwrap();
                    }
                }
                Ok(ty)
            }
            Stmt::While {
                condition,
                body,
                span,
            } => {
                let (cond_src, cond_ty) = self.emit_expr_value(condition)?;
                if cond_ty != CType::Bool {
                    return Err(unsupported("while condition must be Bool", span));
                }
                self.indent_line();
                writeln!(self.out, "while ({}) {{", cond_src).unwrap();
                self.indent += 1;
                self.emit_block(body, return_ty)?;
                self.indent -= 1;
                self.indent_line();
                writeln!(self.out, "}}").unwrap();
                Ok(CType::Unit)
            }
            Stmt::For {
                name,
                iter,
                body,
                span,
            } => {
                // For Phase 1 we only support `for x in <int> .. <int>`.
                let (start_src, end_src) = match iter {
                    Expr::Range { start, end, .. } => {
                        let (s, sty) = self.emit_expr_value(start)?;
                        let (e, ety) = self.emit_expr_value(end)?;
                        if sty != CType::Int || ety != CType::Int {
                            return Err(unsupported(
                                "native codegen: for-in range must be Int..Int",
                                span,
                            ));
                        }
                        (s, e)
                    }
                    _ => {
                        return Err(unsupported(
                            "native codegen: for-in currently requires an integer range (a..b)",
                            span,
                        ));
                    }
                };
                self.indent_line();
                writeln!(
                    self.out,
                    "for (int64_t {var} = {start}; {var} < {end}; ++{var}) {{",
                    var = c_ident(name),
                    start = start_src,
                    end = end_src
                )
                .unwrap();
                self.indent += 1;
                self.push_scope();
                self.declare_local(name, CType::Int)?;
                self.emit_block(body, return_ty)?;
                self.pop_scope();
                self.indent -= 1;
                self.indent_line();
                writeln!(self.out, "}}").unwrap();
                Ok(CType::Unit)
            }
            Stmt::Break { .. } => {
                self.indent_line();
                writeln!(self.out, "break;").unwrap();
                Ok(CType::Unit)
            }
            Stmt::Continue { .. } => {
                self.indent_line();
                writeln!(self.out, "continue;").unwrap();
                Ok(CType::Unit)
            }
        }
    }

    /// Emit an expression that produces a value. Returns (C expression
    /// source, type). The expression is pure C — any statements needed
    /// to compute it have already been emitted to self.out.
    fn emit_expr_value(&mut self, expr: &Expr) -> LangResult<(String, CType)> {
        match expr {
            Expr::Int(value, _) => Ok((format!("INT64_C({})", value), CType::Int)),
            Expr::Bool(value, _) => Ok((
                if *value {
                    "true".to_string()
                } else {
                    "false".to_string()
                },
                CType::Bool,
            )),
            Expr::Unit(_) => Ok(("/* () */ 0".to_string(), CType::Unit)),
            Expr::Float(value, _) => {
                // Round-trip through Rust's standard f64 formatter so we
                // always emit a literal with a decimal point or exponent —
                // C would otherwise read `12` as an int and reject it as
                // a `double` initializer.
                let mut rendered = format!("{value:?}");
                if !rendered.contains('.') && !rendered.contains('e') && !rendered.contains('E') {
                    rendered.push_str(".0");
                }
                Ok((format!("((double){rendered})"), CType::Float))
            }
            Expr::String(_, span) => Err(unsupported(
                "native codegen does not yet support String literals",
                span,
            )),
            Expr::Ident(name, span) => {
                if let Some(ty) = self.lookup_local(name) {
                    Ok((c_ident(name), ty))
                } else if self.functions.contains_key(name) {
                    Err(unsupported(
                        format!("native codegen does not yet support passing function '{name}' as a value"),
                        span,
                    ))
                } else if name == "print" {
                    Err(unsupported(
                        "native codegen requires `print(...)` to be applied directly, not used as a value",
                        span,
                    ))
                } else {
                    Err(codegen_error(format!("unknown name '{name}'"), span))
                }
            }
            Expr::Unary { op, expr, span } => {
                let (inner, ty) = self.emit_expr_value(expr)?;
                match op {
                    UnaryOp::Negate => match ty {
                        CType::Int => Ok((format!("(-({}))", inner), CType::Int)),
                        CType::Float => Ok((format!("(-({}))", inner), CType::Float)),
                        _ => Err(unsupported("unary - requires Int or Float", span)),
                    },
                    UnaryOp::Not => {
                        if ty != CType::Bool {
                            return Err(unsupported("unary ! requires Bool", span));
                        }
                        Ok((format!("(!({}))", inner), CType::Bool))
                    }
                }
            }
            Expr::Binary {
                left,
                op,
                right,
                span,
            } => self.emit_binary(left, *op, right, span),
            Expr::Pipeline { left, right, span } => self.emit_pipeline(left, right, span),
            Expr::Call { callee, args, span } => self.emit_call(callee, args, span),
            Expr::If {
                condition,
                then_branch,
                else_branch,
                span,
            } => self.emit_if(condition, then_branch, else_branch.as_ref(), span),
            Expr::Block(block) => self.emit_block_expression(block),
            Expr::Range { span, .. } => Err(unsupported(
                "native codegen: ranges are only valid as the iterator of a for-in loop",
                span,
            )),
            Expr::Match { span, .. } => Err(unsupported(
                "native codegen does not yet support `match`",
                span,
            )),
            Expr::Lambda { span, .. } => Err(unsupported(
                "native codegen does not yet support lambdas",
                span,
            )),
            Expr::Dict(_, span)
            | Expr::List(_, span)
            | Expr::Index { span, .. }
            | Expr::Field { span, .. }
            | Expr::MethodCall { span, .. }
            | Expr::StructLit { span, .. } => Err(unsupported(
                "native codegen does not yet support data structures (lists / structs / fields)",
                span,
            )),
            Expr::Try { span, .. } | Expr::Spawn { span, .. } | Expr::Await { span, .. } => {
                Err(unsupported(
                    "native codegen: `?`, `spawn`, and `await` arrive in Phase 3",
                    span,
                ))
            }
            Expr::Ref { span, .. } | Expr::Region { span, .. } => Err(unsupported(
                "native codegen: references and regions arrive in Phase 2.1",
                span,
            )),
            Expr::Path(_, span) => Err(unsupported(
                "native codegen does not yet support qualified paths",
                span,
            )),
        }
    }

    fn emit_binary(
        &mut self,
        left: &Expr,
        op: BinaryOp,
        right: &Expr,
        span: &Span,
    ) -> LangResult<(String, CType)> {
        let (l_src, l_ty) = self.emit_expr_value(left)?;
        let (r_src, r_ty) = self.emit_expr_value(right)?;
        let (operator, result_ty) = match op {
            BinaryOp::Add
            | BinaryOp::Subtract
            | BinaryOp::Multiply
            | BinaryOp::Divide
            | BinaryOp::Remainder => {
                let both_int = l_ty == CType::Int && r_ty == CType::Int;
                let both_float = l_ty == CType::Float && r_ty == CType::Float;
                if !both_int && !both_float {
                    return Err(unsupported(
                        "native codegen: arithmetic operators require matching Int or Float operands",
                        span,
                    ));
                }
                if both_float && op == BinaryOp::Remainder {
                    return Err(unsupported(
                        "native codegen: '%' on Float operands is not supported; use a helper",
                        span,
                    ));
                }
                let sym = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Subtract => "-",
                    BinaryOp::Multiply => "*",
                    BinaryOp::Divide => "/",
                    BinaryOp::Remainder => "%",
                    _ => unreachable!(),
                };
                (sym, if both_float { CType::Float } else { CType::Int })
            }
            BinaryOp::Equal | BinaryOp::NotEqual => {
                if l_ty != r_ty {
                    return Err(unsupported(
                        "native codegen: equality requires matching operand types",
                        span,
                    ));
                }
                (if op == BinaryOp::Equal { "==" } else { "!=" }, CType::Bool)
            }
            BinaryOp::Less | BinaryOp::LessEqual | BinaryOp::Greater | BinaryOp::GreaterEqual => {
                let both_int = l_ty == CType::Int && r_ty == CType::Int;
                let both_float = l_ty == CType::Float && r_ty == CType::Float;
                if !both_int && !both_float {
                    return Err(unsupported(
                        "native codegen: comparison operators require matching Int or Float operands",
                        span,
                    ));
                }
                let sym = match op {
                    BinaryOp::Less => "<",
                    BinaryOp::LessEqual => "<=",
                    BinaryOp::Greater => ">",
                    BinaryOp::GreaterEqual => ">=",
                    _ => unreachable!(),
                };
                (sym, CType::Bool)
            }
            BinaryOp::And | BinaryOp::Or => {
                if l_ty != CType::Bool || r_ty != CType::Bool {
                    return Err(unsupported(
                        "native codegen: logical operators require Bool operands",
                        span,
                    ));
                }
                (if op == BinaryOp::And { "&&" } else { "||" }, CType::Bool)
            }
        };

        Ok((format!("({} {} {})", l_src, operator, r_src), result_ty))
    }

    fn emit_pipeline(
        &mut self,
        left: &Expr,
        right: &Expr,
        span: &Span,
    ) -> LangResult<(String, CType)> {
        match right {
            Expr::Call {
                callee,
                args,
                span: cspan,
            } => {
                let mut new_args = Vec::with_capacity(args.len() + 1);
                new_args.push(left.clone());
                new_args.extend(args.iter().cloned());
                self.emit_call(callee, &new_args, cspan)
            }
            Expr::Ident(_, _) => {
                let args = vec![left.clone()];
                self.emit_call(right, &args, span)
            }
            _ => Err(unsupported(
                "native codegen: pipeline rhs must be a function call",
                span,
            )),
        }
    }

    fn emit_call(
        &mut self,
        callee: &Expr,
        args: &[Expr],
        span: &Span,
    ) -> LangResult<(String, CType)> {
        let name = match callee {
            Expr::Ident(name, _) => name.clone(),
            _ => {
                return Err(unsupported(
                    "native codegen: call target must be a top-level function name",
                    span,
                ));
            }
        };

        // Built-in `print`.
        if name == "print" || name == "println" {
            if args.len() != 1 {
                return Err(unsupported("print expects exactly 1 argument", span));
            }
            let (arg_src, arg_ty) = self.emit_expr_value(&args[0])?;
            let helper = match arg_ty {
                CType::Int => "mom_print_int",
                CType::Bool => "mom_print_bool",
                CType::Float => "mom_print_float",
                CType::Unit => "mom_print_unit",
            };
            // print() is a statement, not a value — return the empty
            // sentinel so emit_stmt skips emitting a trailing `;`.
            return Ok((format!("{helper}({arg_src})"), CType::Unit));
        }

        // User-defined function call.
        let sig = self
            .functions
            .get(&name)
            .cloned()
            .ok_or_else(|| codegen_error(format!("unknown function '{name}'"), span))?;
        if sig.params.len() != args.len() {
            return Err(codegen_error(
                format!(
                    "function '{}' expects {} argument(s), got {}",
                    name,
                    sig.params.len(),
                    args.len()
                ),
                span,
            ));
        }
        let mut arg_srcs = Vec::with_capacity(args.len());
        for (arg, (_pname, expected_ty)) in args.iter().zip(sig.params.iter()) {
            let (src, ty) = self.emit_expr_value(arg)?;
            if ty != *expected_ty {
                return Err(unsupported(
                    format!(
                        "native codegen: argument to '{}' has type {:?}, expected {:?}",
                        name, ty, expected_ty
                    ),
                    &arg.span(),
                ));
            }
            arg_srcs.push(src);
        }
        let call = format!("{}({})", c_ident(&name), arg_srcs.join(", "));
        Ok((call, sig.return_ty))
    }

    fn emit_if(
        &mut self,
        condition: &Expr,
        then_branch: &Block,
        else_branch: Option<&Block>,
        span: &Span,
    ) -> LangResult<(String, CType)> {
        let (cond_src, cond_ty) = self.emit_expr_value(condition)?;
        if cond_ty != CType::Bool {
            return Err(unsupported("if condition must be Bool", span));
        }

        // Determine the if-expression type by inspecting tail expressions.
        let result_ty = infer_block_tail_type(then_branch)
            .or_else(|| else_branch.and_then(infer_block_tail_type))
            .unwrap_or(CType::Unit);

        if result_ty == CType::Unit {
            // statement-form if
            self.indent_line();
            writeln!(self.out, "if ({}) {{", cond_src).unwrap();
            self.indent += 1;
            self.emit_block(then_branch, result_ty)?;
            self.indent -= 1;
            if let Some(else_branch) = else_branch {
                self.indent_line();
                writeln!(self.out, "}} else {{").unwrap();
                self.indent += 1;
                self.emit_block(else_branch, result_ty)?;
                self.indent -= 1;
            }
            self.indent_line();
            writeln!(self.out, "}}").unwrap();
            Ok(("/* if-stmt */ 0".to_string(), CType::Unit))
        } else {
            // value-form if — synthesise a temp
            let temp = self.fresh_temp();
            self.indent_line();
            writeln!(self.out, "{} {};", result_ty.c_repr(), temp).unwrap();
            self.indent_line();
            writeln!(self.out, "if ({}) {{", cond_src).unwrap();
            self.indent += 1;
            self.emit_block_assigning(then_branch, &temp, result_ty)?;
            self.indent -= 1;
            self.indent_line();
            if let Some(else_branch) = else_branch {
                writeln!(self.out, "}} else {{").unwrap();
                self.indent += 1;
                self.emit_block_assigning(else_branch, &temp, result_ty)?;
                self.indent -= 1;
                self.indent_line();
            }
            writeln!(self.out, "}}").unwrap();
            Ok((temp, result_ty))
        }
    }

    /// Emit a block whose tail expression is captured into `temp`.
    fn emit_block_assigning(
        &mut self,
        block: &Block,
        temp: &str,
        expected_ty: CType,
    ) -> LangResult<()> {
        self.push_scope();
        let len = block.statements.len();
        for (idx, stmt) in block.statements.iter().enumerate() {
            let is_last = idx + 1 == len;
            if is_last {
                if let Stmt::Expr {
                    expr,
                    has_semicolon: false,
                    ..
                } = stmt
                {
                    let (src, ty) = self.emit_expr_value(expr)?;
                    if ty != expected_ty {
                        return Err(unsupported(
                            "native codegen: branch types of an if-expression must match",
                            &expr.span(),
                        ));
                    }
                    self.indent_line();
                    writeln!(self.out, "{} = {};", temp, src).unwrap();
                    self.pop_scope();
                    return Ok(());
                }
            }
            self.emit_stmt(stmt, false, expected_ty)?;
        }
        // No tail expression — leave the temp at its existing value.
        self.pop_scope();
        Ok(())
    }

    fn emit_block_expression(&mut self, block: &Block) -> LangResult<(String, CType)> {
        // Determine result type from tail expression.
        let tail_ty = infer_block_tail_type(block).unwrap_or(CType::Unit);
        if tail_ty == CType::Unit {
            self.indent_line();
            writeln!(self.out, "{{").unwrap();
            self.indent += 1;
            self.emit_block(block, CType::Unit)?;
            self.indent -= 1;
            self.indent_line();
            writeln!(self.out, "}}").unwrap();
            Ok(("/* block */ 0".to_string(), CType::Unit))
        } else {
            let temp = self.fresh_temp();
            self.indent_line();
            writeln!(self.out, "{} {};", tail_ty.c_repr(), temp).unwrap();
            self.indent_line();
            writeln!(self.out, "{{").unwrap();
            self.indent += 1;
            self.emit_block_assigning(block, &temp, tail_ty)?;
            self.indent -= 1;
            self.indent_line();
            writeln!(self.out, "}}").unwrap();
            Ok((temp, tail_ty))
        }
    }

    fn push_scope(&mut self) {
        self.locals.push(HashMap::new());
    }

    fn pop_scope(&mut self) {
        self.locals.pop();
    }

    fn declare_local(&mut self, name: &str, ty: CType) -> LangResult<()> {
        if let Some(scope) = self.locals.last_mut() {
            scope.insert(name.to_string(), ty);
        }
        Ok(())
    }

    fn lookup_local(&self, name: &str) -> Option<CType> {
        for scope in self.locals.iter().rev() {
            if let Some(ty) = scope.get(name) {
                return Some(*ty);
            }
        }
        None
    }

    fn fresh_temp(&mut self) -> String {
        self.temp_counter += 1;
        format!("__mom_tmp_{}", self.temp_counter)
    }

    fn indent_line(&mut self) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
    }
}

impl Default for Codegen {
    fn default() -> Self {
        Self::new()
    }
}

/// Best-effort tail-type inference for a block — only looks at the last
/// statement. Used to decide if an if/block is value-form or
/// statement-form before we walk it.
fn infer_block_tail_type(block: &Block) -> Option<CType> {
    let last = block.statements.last()?;
    match last {
        Stmt::Expr {
            expr,
            has_semicolon: false,
            ..
        } => infer_expr_type(expr),
        _ => None,
    }
}

fn infer_expr_type(expr: &Expr) -> Option<CType> {
    match expr {
        Expr::Int(_, _) => Some(CType::Int),
        Expr::Bool(_, _) => Some(CType::Bool),
        Expr::Unit(_) => Some(CType::Unit),
        Expr::Binary { op, .. } => match op {
            BinaryOp::Add
            | BinaryOp::Subtract
            | BinaryOp::Multiply
            | BinaryOp::Divide
            | BinaryOp::Remainder => Some(CType::Int),
            _ => Some(CType::Bool),
        },
        Expr::Unary { op, .. } => Some(match op {
            UnaryOp::Negate => CType::Int,
            UnaryOp::Not => CType::Bool,
        }),
        Expr::If { then_branch, .. } => infer_block_tail_type(then_branch),
        Expr::Block(b) => infer_block_tail_type(b),
        Expr::Ident(_, _) | Expr::Call { .. } | Expr::Pipeline { .. } => None,
        _ => None,
    }
}

fn c_ident(name: &str) -> String {
    // mom names are already valid C identifiers (ascii letters, digits,
    // underscore). Reserved C keywords are namespaced to avoid collision.
    if is_c_reserved(name) {
        format!("mom_{name}")
    } else {
        name.to_string()
    }
}

fn is_c_reserved(name: &str) -> bool {
    matches!(
        name,
        "auto"
            | "break"
            | "case"
            | "char"
            | "const"
            | "continue"
            | "default"
            | "do"
            | "double"
            | "else"
            | "enum"
            | "extern"
            | "float"
            | "for"
            | "goto"
            | "if"
            | "inline"
            | "int"
            | "long"
            | "register"
            | "restrict"
            | "return"
            | "short"
            | "signed"
            | "sizeof"
            | "static"
            | "struct"
            | "switch"
            | "typedef"
            | "union"
            | "unsigned"
            | "void"
            | "volatile"
            | "while"
            | "main"
    )
}

fn codegen_error(message: impl Into<String>, span: &Span) -> Diagnostic {
    Diagnostic::new(message, span.clone())
}

fn unsupported(message: impl Into<String>, span: &Span) -> Diagnostic {
    Diagnostic::new(message, span.clone())
}
