use crate::diagnostic::Span;

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}

impl Token {
    pub fn new(kind: TokenKind, span: Span) -> Self {
        Self { kind, span }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Ident(String),
    Int(i64),
    Float(f64),
    String(String),
    Keyword(Keyword),
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    DotDot,
    Colon,
    ColonColon,
    Semicolon,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Bang,
    Amp,
    Question,
    Equal,
    Less,
    Greater,
    EqualEqual,
    BangEqual,
    LessEqual,
    GreaterEqual,
    AndAnd,
    OrOr,
    Pipe,
    PipeForward,
    Arrow,
    FatArrow,
    Hash,
    Eof,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Keyword {
    Actor,
    As,
    Async,
    Await,
    Break,
    Comptime,
    Const,
    Continue,
    Defer,
    Else,
    Enum,
    Extern,
    False,
    Fn,
    For,
    From,
    If,
    Impl,
    Import,
    In,
    Let,
    Match,
    Module,
    Mut,
    Pub,
    Receive,
    Region,
    Return,
    Self_,
    Spawn,
    Struct,
    Supervise,
    Trait,
    True,
    Type,
    Unsafe,
    Use,
    Where,
    While,
}

impl Keyword {
    pub fn from_ident(ident: &str) -> Option<Self> {
        match ident {
            "actor" => Some(Self::Actor),
            "as" => Some(Self::As),
            "async" => Some(Self::Async),
            "await" => Some(Self::Await),
            "break" => Some(Self::Break),
            "comptime" => Some(Self::Comptime),
            "const" => Some(Self::Const),
            "continue" => Some(Self::Continue),
            "defer" => Some(Self::Defer),
            "else" => Some(Self::Else),
            "enum" => Some(Self::Enum),
            "extern" => Some(Self::Extern),
            "false" => Some(Self::False),
            "fn" => Some(Self::Fn),
            "for" => Some(Self::For),
            "from" => Some(Self::From),
            "if" => Some(Self::If),
            "impl" => Some(Self::Impl),
            "import" => Some(Self::Import),
            "in" => Some(Self::In),
            "let" => Some(Self::Let),
            "match" => Some(Self::Match),
            "module" => Some(Self::Module),
            "mut" => Some(Self::Mut),
            "pub" => Some(Self::Pub),
            "receive" => Some(Self::Receive),
            "region" => Some(Self::Region),
            "return" => Some(Self::Return),
            "self" => Some(Self::Self_),
            "spawn" => Some(Self::Spawn),
            "struct" => Some(Self::Struct),
            "supervise" => Some(Self::Supervise),
            "trait" => Some(Self::Trait),
            "true" => Some(Self::True),
            "type" => Some(Self::Type),
            "unsafe" => Some(Self::Unsafe),
            "use" => Some(Self::Use),
            "where" => Some(Self::Where),
            "while" => Some(Self::While),
            _ => None,
        }
    }
}
